import { INFT } from "./interfaces/INFT.ts";

export const NFTS: INFT[] = [
  {
    id: 1,
    image: "X",
    name: "title",
    autor: "Ishak",
    typePrice: 1,
    price: "100",
  },
  {
    id: 2,
    image: "X",
    name: "The Holy Grail",
    autor: "Pixart Motion",
    typePrice: 2,
    price: "0.001",
  },
  {
    id: 3,
    image: "X",
    name: "The Holy Grail",
    autor: "Pixart Motion",
    typePrice: 1,
    price: "0.001",
  },
  {
    id: 4,
    image: "X",
    name: "The Holy Grail",
    autor: "Pixart Motion",
    typePrice: 2,
    price: "0.001",
  },
  {
    id: 5,
    image: "X",
    name: "The Holy Grail",
    autor: "Pixart Motion",
    typePrice: 1,
    price: "0.001",
  },
  {
    id: 6,
    image: "X",
    name: "The Holy Grail",
    autor: "Pixart Motion",
    typePrice: 1,
    price: "0.001",
  },
  {
    id: 7,
    image: "X",
    name: "The Holy Grail",
    autor: "Pixart Motion",
    typePrice: 2,
    price: "0.001",
  },
  {
    id: 8,
    image: "X",
    name: "8",
    autor: "Pixart Motion",
    typePrice: 1,
    price: "0.001",
  },
  // {
  //   id: 9,
  //   photo: "X",
  //   title: "9",
  //   author: "Pixart Motion",
  //   type: "cat",
  //   priceType: "Fixed",
  //   price: 0.001,
  // },
  // {
  //   id: 10,
  //   photo: "X",
  //   title: "10",
  //   author: "Pixart Motion",
  //   type: "cat",
  //   priceType: "Fixed",
  //   price: 0.001,
  // },
];
